
fastlane_version "2.53.1"

default_platform :ios

platform :ios do
  before_all do
  end

  desc "Runs all the tests"
  lane :test do
    scan(
      scheme: "SerialHttpRequest",
      clean: true,
      device: "iPhone 6",
      output_types: "html",
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
  end

  desc "Deploy a new version to the App Store"
  lane :release do
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end
